AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB backend for my personal page
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - production
Resources:
  QuotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Quotes
      AttributeDefinitions:
        -
          AttributeName: author
          AttributeType: S
        -
          AttributeName: quote
          AttributeType: S
      KeySchema:
        -
          AttributeName: quote
          KeyType: HASH       
        -
          AttributeName: author
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
  AuditTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Audit
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: email
          AttributeType: S
        -
          AttributeName: timestamp
          AttributeType: S
        -
          AttributeName: name
          AttributeType: S
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH       
        -
          AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
Outputs:
  QuotesTable:
    Description: Quotes table created with this template
    Value: !Ref QuotesTable
  AuditTable:
    Description: Audit table created with this template
    Value: !Ref AuditTable